/**
 * HTML shell for Orbital. `renderHTML` takes the stylesheet and the
 * (type-stripped) simulation script and returns a complete, standalone
 * single-file document. Called by `build.ts`.
 */

export interface RenderInput {
  css: string;
  js: string;
}

/** The static markup the simulation script binds to. */
const BODY = `
<canvas id="scene"></canvas>

<div id="dash">
  <div class="title"><span class="dot"></span><h1>Orbital</h1><button id="closeDash" aria-label="Close panel">×</button></div>
  <div class="subtitle">An interactive N-body solar system. Tune the physics and watch orbits respond.</div>

  <div class="group">
    <div class="group-label">Simulation</div>
    <div class="ctrl">
      <div class="ctrl-head"><label>Time speed</label><span class="val" id="v_speed">0.10×</span></div>
      <input type="range" id="s_speed" min="0" max="50" value="10">
    </div>
    <div class="ctrl">
      <div class="ctrl-head"><label>Gravity (G)</label><span class="val" id="v_grav">1.00×</span></div>
      <input type="range" id="s_grav" min="0" max="300" value="100">
    </div>
    <div class="ctrl">
      <div class="ctrl-head"><label>Sun mass</label><span class="val" id="v_sun">1.00×</span></div>
      <input type="range" id="s_sun" min="10" max="300" value="100">
    </div>
    <div class="btn-row">
      <button class="b" id="b_pause">⏸ Pause</button>
      <button class="b" id="b_reset">↺ Reset</button>
    </div>
  </div>

  <div class="group">
    <div class="group-label">View</div>
    <div class="ctrl">
      <div class="ctrl-head"><label>Zoom</label><span class="val" id="v_zoom">1.00×</span></div>
      <input type="range" id="s_zoom" min="20" max="400" value="100">
    </div>
    <div class="toggle-row"><label for="t_trails">Orbit trails</label>
      <label class="switch"><input type="checkbox" id="t_trails" checked><span class="slider-sw"></span></label></div>
    <div class="toggle-row"><label for="t_orbits">Orbit paths</label>
      <label class="switch"><input type="checkbox" id="t_orbits" checked><span class="slider-sw"></span></label></div>
    <div class="toggle-row"><label for="t_labels">Labels</label>
      <label class="switch"><input type="checkbox" id="t_labels" checked><span class="slider-sw"></span></label></div>
    <div class="toggle-row"><label for="t_realscale">Realistic scale</label>
      <label class="switch"><input type="checkbox" id="t_realscale"><span class="slider-sw"></span></label></div>
    <div class="toggle-row"><label for="t_collide">Collisions (merge)</label>
      <label class="switch"><input type="checkbox" id="t_collide" checked><span class="slider-sw"></span></label></div>
  </div>

  <div class="group">
    <div class="group-label">Focus body</div>
    <select class="sel" id="sel_focus"></select>
    <div class="hint">Drag to pan · Scroll to zoom · Click a body to focus &middot; <b>Both buttons drag to tilt/spin</b> &middot; Press <b>0</b> to reset view.<br><b>Touch:</b> drag to pan &middot; pinch to zoom &middot; two fingers to tilt/spin &middot; tap to focus.</div>
  </div>

  <div class="group">
    <div class="group-label">Experiments</div>
    <div class="btn-row">
      <button class="b" id="b_zerog">Zero-G</button>
      <button class="b" id="b_kick">Kick planets</button>
      <button class="b" id="b_comet">Add comet</button>
    </div>
  </div>

  <div class="credit">Generated from TypeScript · vanilla JS + Canvas</div>
</div>
<button id="toggleDash">☰</button>

<div id="readout"></div>
<div id="tip"></div>`;

export function renderHTML({ css, js }: RenderInput): string {
  return `<!DOCTYPE html>
<!--
  AUTO-GENERATED by build.ts — do not edit directly.
  Edit src/main.ts / src/styles.css / src/template.ts and run \`npm run build\`.
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no, viewport-fit=cover">
<title>Orbital — Solar System Simulator</title>
<style>
${css.trim()}
</style>
</head>
<body>
${BODY.trim()}

<script>
${js.trim()}
</script>
</body>
</html>
`;
}
